services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    build:
      context: .
      args:
        GROUPID: 1000 # Replace with output of `id -g`
        GROUPNAME: yourgroup # Replace with output of `id -gn`
        USERID: 1000 # Replace with output of `id -u`
        USERNAME: youruser # Replace with your username
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
